# Generated by Django 3.0.7 on 2020-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(default='Chilena', max_length=40),
            preserve_default=False,
        ),
    ]
