# Generated by Django 3.0.7 on 2020-06-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0002_author_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='api_books.Books', verbose_name='Libros'),
        ),
    ]
