# Generated by Django 3.0.7 on 2020-06-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0003_auto_20200615_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
